on:
    workflow_dispatch:
    push:
        branches:
            - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "*"
            - run: npm update

            # Validate code.
            - run: npx tsc
            - run: npx eslint app tests
            - run: npx ava tests/js/test*.js

            # Generate pages.
            - run: node build.js --path "/inat-tools/"

            - uses: actions/upload-pages-artifact@v3
              with:
                  path: "public/"
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
