on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "*"
            - run: npm update

            # Validate code.
            - run: npm run check
    build:
        runs-on: ubuntu-latest
        if: ${{ github.event_name != 'pull_request' }}
        needs: test
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "*"
            - run: npm update

            # Generate pages.
            - run: node scripts/int-build.js --no-watch
            - run: npx parcel build --dist-dir public --public-url /inat-tools --no-source-maps

            - uses: actions/upload-pages-artifact@v3
              with:
                  path: "public/"
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        if: ${{ github.event_name != 'pull_request' }}
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
